import type { Province } from "./types"

export const provinces: Province[] = [
  {
    id: "1",
    name: "Ontario",
    slug: "ontario",
    image: "/ontario-cn-tower.jpg",
    description: "Handbook-backed Ontario practice questions",
    coverageLevel: "handbook-backed",
  },
  {
    id: "2",
    name: "Alberta",
    slug: "alberta",
    image: "/alberta-rocky-mountains.jpg",
    description: "Handbook-backed Alberta practice questions",
    coverageLevel: "handbook-backed",
  },
  {
    id: "3",
    name: "British Columbia",
    slug: "british-columbia",
    image: "/bc-coastal-mountains.jpg",
    description: "BC practice questions based on ICBC handbook topics",
    coverageLevel: "handbook-aligned",
  },
  {
    id: "4",
    name: "Quebec",
    slug: "quebec",
    image: "/quebec-chateau-frontenac.jpg",
    description: "General practice questions for Quebec drivers",
    coverageLevel: "general-practice",
  },
  {
    id: "5",
    name: "Manitoba",
    slug: "manitoba",
    image: "/manitoba-winnipeg.jpg",
    description: "General practice questions for Manitoba drivers",
    coverageLevel: "general-practice",
  },
  {
    id: "6",
    name: "Saskatchewan",
    slug: "saskatchewan",
    image: "/saskatchewan-golden-wheat-field.jpg",
    description: "Handbook-backed Saskatchewan practice questions",
    coverageLevel: "handbook-backed",
  },
  {
    id: "7",
    name: "Nova Scotia",
    slug: "nova-scotia",
    image: "/nova-scotia-lighthouse.jpg",
    description: "General practice questions for Nova Scotia drivers",
    coverageLevel: "general-practice",
  },
  {
    id: "8",
    name: "New Brunswick",
    slug: "new-brunswick",
    image: "/new-brunswick-fundy-cliffs.jpg",
    description: "General practice questions for New Brunswick drivers",
    coverageLevel: "general-practice",
  },
  {
    id: "9",
    name: "Newfoundland and Labrador",
    slug: "newfoundland-labrador",
    image: "/newfoundland-coastal-cliffs.jpg",
    description: "General practice questions for Newfoundland and Labrador drivers",
    coverageLevel: "general-practice",
  },
  {
    id: "10",
    name: "Prince Edward Island",
    slug: "prince-edward-island",
    image: "/pei-red-sand-beach.jpg",
    description: "General practice questions for PEI drivers",
    coverageLevel: "general-practice",
  },
  {
    id: "11",
    name: "Northwest Territories",
    slug: "northwest-territories",
    image: "/nwt-northern-lights-landscape.jpg",
    description: "General practice questions for Northwest Territories drivers",
    coverageLevel: "general-practice",
  },
  {
    id: "12",
    name: "Yukon",
    slug: "yukon",
    image: "/yukon-mountains.jpg",
    description: "General practice questions for Yukon drivers",
    coverageLevel: "general-practice",
  },
  {
    id: "13",
    name: "Nunavut",
    slug: "nunavut",
    image: "/nunavut-ice-landscape.jpg",
    description: "General practice questions for Nunavut drivers",
    coverageLevel: "general-practice",
  },
]

export const handbookCoverageNote = "Ontario, Alberta, and Saskatchewan now use handbook-backed question sets. British Columbia uses handbook-aligned practice coverage, and the remaining provinces currently use general practice sets until official guide coverage is expanded."

/* Question bank moved to lib/questions.ts */
